# Color term
set -g default-terminal "screen-256color"
set-option -sa terminal-overrides ',xterm-256color:RGB'

# set-option -ga terminal-overrides ",xterm-256-color:RGB"

# Focus events
set-option -g focus-events on

# Reload this configuration
unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"

# Speed up escape time, for vim
set -s escape-time 0

# Prefix mapping
set-option -g prefix C-z
bind C-z send-prefix
unbind C-b

# Mouse works as expected
setw -g mouse on

set -g mode-keys vi
set -g history-limit 10000

# Pane splitting
unbind v
unbind h
unbind %  # Default vertical
unbind '"'  # Default horizontal
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"

# Pane navigation
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Copy and past as in vim
bind Escape copy-mode
unbind p
bind p paste-buffer
bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send -X copy-selection
